#!/usr/bin/env zsh
#                     ██
#                    ░██
#      ██████  ██████░██████   █████  ██████  ██    ██
#     ░░░░██  ██░░░░ ░██░░░██ ██░░░██░██░░░██░██   ░██
#        ██  ░░█████ ░██  ░██░███████░██  ░██░░██ ░██
#       ██    ░░░░░██░██  ░██░██░░░░ ░██  ░██ ░░████
#  ██  ██████ ██████ ░██  ░██░░█████ ░██  ░██  ░░██
# ░░  ░░░░░░ ░░░░░░  ░░   ░░  ░░░░░  ░░   ░░    ░░
#

# XDG base directory:
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

if [[ -z "${COLORTERM}" ]]; then
  export COLORTERM="truecolor"
fi

if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
