"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
  append_keymap = [
    { on = "H", run = "tab_switch -1 --relative", desc = "Switch to the previous tab" },
    { on = "L", run = "tab_switch 1 --relative", desc = "Switch to the next tab" },
    { on = "<", run = "tab_swap -1", desc = "Swap current tab with previous tab" },
    { on = ">", run = "tab_swap 1", desc = "Swap current tab with next tab" },
  ]
  prepend_keymap = [
    # Wait for 25.6.1
    # { on = "+", run = "plugin zoom 1", desc = "Zoom in hovered file" },
    # { on = "-", run = "plugin zoom -1", desc = "Zoom out hovered file" },
  ]
