#:schema https://mise.jdx.dev/schema/mise.json

[settings]
  color_theme                  = "catppuccin"
  github_attestations          = false
  cargo.binstall               = true
  npm.package_manager          = "bun"
  pipx.uvx                     = true
  minimum_release_age_excludes = ["ty", "tsgo"]

[tool_alias]
  # LSP
  marksman  = "aqua:artempyanykh/marksman"  # Markdown
  harper_ls = "aqua:Automattic/harper/harper-ls"  # English
  tinymist  = "aqua:Myriad-Dreamin/tinymist"  # Typst
  tombi     = "aqua:tombi-toml/tombi"  # TOML

  ty          = "github:astral-sh/ty"  # Python
  clangd      = "github:clangd/clangd"  # C++
  emmylua_ls  = "github:EmmyLuaLs/emmylua-analyzer-rust"  # Lua
  ts_query_ls = "github:ribru17/ts_query_ls"  # Treesitter Query

  jdtls = "http:jdtls"  # Java

  astro_ls     = "npm:@astrojs/language-server"  # Astro
  bash_ls      = "npm:bash-language-server"  # Bash
  copilot      = "npm:@github/copilot-language-server"  # Copilot
  mdx_analyzer = "npm:@mdx-js/language-server"  # MDX
  tailwind_ls  = "npm:@tailwindcss/language-server"  # Tailwind
  tsgo         = "npm:@typescript/native-preview"  # Typescript
  json_ls      = "npm:vscode-langservers-extracted"  # JSON
  yaml_ls      = "npm:yaml-language-server"  # YAML

  # Formatter
  biome  = "aqua:biomejs/biome"  # Astro (temp)
  stylua = "aqua:JohnnyMorganz/StyLua"  # Lua
  shfmt  = "aqua:mvdan/sh"  # Bash

  luafmt = "github:EmmyLuaLs/emmylua-analyzer-rust"  # Lua

  bibtex-tidy = "npm:bibtex-tidy"  # Bibtex
  oxfmt       = "npm:oxfmt"  # TS, TSX, JSON, CSS, YAML, Markdown, MDX

  clang_format = "pipx:clang-format"  # C++, Java

  # Linter
  ruff = "aqua:astral-sh/ruff"  # Python

  # Tools
  tree-sitter = "aqua:tree-sitter/tree-sitter"

  # Windows Tools
  yasb    = "github:amnweb/yasb"
  glazewm = "github:glzr-io/glazewm"

[tools]
  astro_ls     = "latest"
  bash_ls      = "latest"
  clangd       = "latest"
  copilot      = "latest"
  emmylua_ls   = { version = "latest", platforms = { linux-x64 = { asset_pattern = "emmylua_ls-linux-x64-*.tar.gz" } } }
  harper_ls    = "latest"
  jdtls        = {
    version  = "1.58.0",
    url      = "https://download.eclipse.org/jdtls/milestones/{{ version }}/jdt-language-server-{{ version }}-202604151538.tar.gz",
    bin_path = "bin"
  }
  json_ls      = "latest"
  marksman     = "latest"
  mdx_analyzer = "latest"
  tailwind_ls  = "latest"
  tinymist     = "latest"
  tombi        = "latest"
  ts_query_ls  = "latest"
  tsgo         = "latest"
  ty           = "latest"
  yaml_ls      = "latest"

  # Formatter
  bibtex-tidy  = "latest"
  biome        = "latest"
  clang_format = "latest"
  luafmt       = { version = "latest", platforms = { linux-x64 = { asset_pattern = "luafmt-linux-x64-*.tar.gz" } } }
  oxfmt        = "latest"
  shfmt        = "latest"
  stylua       = "latest"

  # Linter
  ruff = "latest"

  # Tools
  tree-sitter = "latest"

  # Windows Tools
  yasb    = {
    version       = "latest",
    asset_pattern = "*-x64.msi",
    bin           = "yasb.msi",
    postinstall   = '''
    install_msi $MISE_TOOL_INSTALL_PATH yasb.msi --helper=yasbc --stop_cmd="stop" --start_cmd="start"
    '''
  }
  glazewm = {
    version       = "latest",
    asset_pattern = "standalone-*-x64.msi",
    bin           = "glazewm.msi",
    postinstall   = '''
    install_msi $MISE_TOOL_INSTALL_PATH glazewm.msi --helper=glazewm --stop_cmd="command wm-exit" --start_cmd="start"
    '''
  }
